- title: "그래프신경망을 활용한 창업 혁신 생태계와 공급 사슬망 구조 분석을 위한 시각적 비즈니스 인텔리전스 시스템 기술 연구"
  image: "newResearch.png"
  description: >
    본 과제에서는 창업 생태계와 관련된 기업, 투자자, 그리고 근로자의 관점에서 정보 네트워크를 구성하고
    그래프 신경망(Graph Neural Network; GNN) 모델을 적용해 기업의 혁신 활동을 분석하고자 합니다.
    또한 창업 생태계와 GNN 모델을 시각적으로 탐색 및 분석할 수 있는 시스템을 개발하여 데이터와 모델을
    탐색하는데 도움을 주고자 합니다.
  date: "2022.03 ~ 2027.02"
  organization: "과학기술정보통신부"

- title: "여론조사 팩트체크 사이트 Poll-A 개발"
  image: "polla.png"
  description: >
    선거가 다가오면 쏟아지는 제각각 여론조사, Poll-A(폴에이)를 통해 여론조사 기관의 경향성을 최소화하고
    정확성을 높인 분석으로 여론의 흐름을 유권자가 직접 확인해 볼 수 있도록 했습니다.
  date: "2023.08 ~ 2024.12"
  organization: "Poll-A"

- title: "자동차산업미래기술혁신을위한오픈플랫폼생태계구축"
  image: "default_proj.png"
  description: >
    자동차 산업 데이터를 제공하기 위한 공공 데이터 포털을 구축하고 운영 관리에 필요한 기술을 개발합니다.
  date: "2021.04 ~ 2023.12"
  organization: "한국자동차연구원"

- title: "SRE Process 자동화를 위한 FAB 네트워크 시각화 및 의사결정 시스템 개발"
  image: "samsung.png"
  description: >
    Betweenness centrality를 활용하여 반도체 FAB 내 OHT railway network의 취약 구간을 파악합니다.
  date: "2023.03 ~ 2026.02"
  organization: "Samsung"

- title: "경제안보: 지수개발과 현황정리"
  image: "EconomicSecurityCluster.png"
  description: >
    본 연구는 국제경제질서의 변화를 분석하고 예측하기 위해 정성적 및 정량적 연구를 진행합니다.
    이를 위해 한국과 주요 국가 간의 수출입 관계를 파악하고, 경제안보 지수를 개발하여 각국과 산업의
    위험을 비교 가능한 형태로 제시합니다.
  date: "2022.06 ~ "
  organization: "서울대학교"

- title: "자산의 위협 탐지를 위한 행동 패턴 클러스터링 및 이상탐지"
  image: "default_proj.png"
  description: >
    안랩의 로그 데이터를 사용하여 행동 패턴과 특징에 따라 자산을 클러스터링한 후 클러스터를 내에서
    이상치 탐지를 진행함으로써 직군별, 분야별 자산의 패턴 하에서 이상 행동을 탐지하도록 합니다.
  date: "2023.08 ~ 2023.10"
  organization: "안랩"

- title: "대사체-의료 빅데이터 기반 약물 반응성 예측 기술 개발 연구"
  image: "default_proj.png"
  description: >
    대규모 바이오뱅크를 활용해 대사체 기반으로 약물 반응성 및 독성을 예측하는 연구를 진행합니다.
  date: "2023-02-01 ~ 2025-11-30"
  organization: "식품의약품안전처"

- title: "네이버쇼핑 행동 유형 모델링 기반 UX개선 연구"
  image: "default_proj.png"
  description: >
    네이버 쇼핑 로그 데이터를 클러스터링함으로써 고객들의 성향 연구 및 네이버 쇼핑몰 UX 개선 솔루션을 도출합니다.
  date: "2022-04-07 ~ 2022-09-28"
  organization: "네이버(주)"

- title: "DA/BI 서비스 고도화를 위한 정형적/비정형적 데이터 분석 모델 개발"
  image: "default_proj.png"
  description: >
    기업 내부 데이터를 분석 및 탐색하기 위하여 시차를 고려한 상관관계 분석 및 이를 바탕으로 변수들의 네트워크 시각화와 클러스터링 탐색 툴 개발
  date: "2021.10.11 ~ 2022.02.25"
  organization: "주식회사 하이퍼라운지"

# - title: "Puddle formation, persistent gaps, and non-mean-field breakdown of superconductivity in overdoped (Pb,Bi)2Sr2CuO6+δ"
#   image: BSCCOgap.png
#   description: Why does cuprate superconductivity break down at a certain doping level? Using scanning tunneling spectroscopy we find that an emerging metallic matrix inside the superconducting state is responsible for the overall reduction of Tc and the superfluid density, while leaving the gapsize unchanged. The formation of the matrix is tied to a pair breaking process violating a core principle of mean-field theories.
#   authors: WO Tromp, T Benschop, J-F Ge, I Battisti, KM Bastiaans, D Chatzopoulos, A Vervloet, S Smit, E van Heumen, MS Golden, Y Huang, T Kondo, Y Yin, JE Hoffman, MA Sulangi, J Zaanen, MP Allan
#   link:
#     url: https://www.nature.com/articles/s41563-023-01497-1
#     display: Nature Materials 22, 703 (2023)
#   highlight: 1
#   news1: See [News and Views](https://www.nature.com/articles/s41563-023-01552-x) by Yu He.
